Document: metamorph
Title: Debian metamorph Manual
Author: <insert document author here>
Abstract: This manual describes what metamorph is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/metamorph/metamorph.sgml.gz

Format: postscript
Files: /usr/share/doc/metamorph/metamorph.ps.gz

Format: text
Files: /usr/share/doc/metamorph/metamorph.text.gz

Format: HTML
Index: /usr/share/doc/metamorph/html/index.html
Files: /usr/share/doc/metamorph/html/*.html
